### ISSUE TITLE
css to tailwind converter doesn't handle background-size correctly

### ISSUE THREAD

**Issue by JLarky** [ritz078/transform#369]
https://transform.tools/css-to-tailwind

input:
```css
.foo {
  background-size: 200% 200%;
}
```

output:
```css
.foo {
  @apply bg-[200%_200%];
}
```

expected output:
```css
.foo {
  @apply bg-[length:200%_200%];
}
```
