### ISSUE TITLE
sr-only

### ISSUE THREAD

**Issue by MoulatiMehdi** [ritz078/transform#381]
i just want to highlight  that sr-only isn't covered by the transformer : 

```css
.selector{   
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
  }
```

it should be : 

```css

.selector{
  @apply  sr-only 
}```
